services:
  - type: web
    name: telegram-gpt-rss-final
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
    autoDeploy: true
